# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"setDefaults": "00_core.ipynb",
         "ROOT": "00_core.ipynb",
         "CONFIRMED": "00_core.ipynb",
         "DEATHS": "00_core.ipynb",
         "RECOVERED": "00_core.ipynb",
         "getToday": "00_core.ipynb",
         "getYesterday": "00_core.ipynb",
         "procDataframe": "00_core.ipynb",
         "procUrl": "00_core.ipynb",
         "getCountriesDailyReport": "00_core.ipynb",
         "plotCountriesDailyReport": "00_core.ipynb",
         "getTimeSeriesConfirmed": "00_core.ipynb",
         "getTimeSeriesDeaths": "00_core.ipynb",
         "getTimeSeriesRecovered": "00_core.ipynb",
         "procTimeSeriesDataframe": "00_core.ipynb",
         "procTimeSeries": "00_core.ipynb",
         "procTimeSeriesDeaths": "00_core.ipynb",
         "procTimeSeriesConfirmed": "00_core.ipynb",
         "plotCountryTimeSeries": "00_core.ipynb",
         "plotCountriesDailyReportFromAPI": "00_core.ipynb",
         "plotCategoryByCountry": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://malminhas.github.io/covid/"

git_url = "https://github.com/malminhas/covid/tree/master/"

def custom_doc_links(name): return None
